/**
 * estado.js — Constantes de estados de la máquina de tanqueo v2
 * Módulo: Tanqueo con OCR y validación cruzada
 * CERO — Gestión de Operaciones de Campo
 */

'use strict';

var ESTADOS = {
  INICIO: 'TANQUEO_INICIO',
  TIPO_TANQUEO: 'TANQUEO_TIPO_TANQUEO', // Elección convenio / emergencia
  ESPERANDO_FOTO_FACTURA: 'TANQUEO_ESPERANDO_FOTO_FACTURA',
  ESPERANDO_FOTO_PLACA: 'TANQUEO_ESPERANDO_FOTO_PLACA',
  PLACA_CONFIRMACION_SUGERIDA: 'TANQUEO_PLACA_CONFIRMACION_SUGERIDA',
  PLACA_FALLBACK: 'TANQUEO_PLACA_FALLBACK',
  PLACA_MANUAL: 'TANQUEO_PLACA_MANUAL',
  ESPERANDO_FOTO_ODOMETRO: 'TANQUEO_ESPERANDO_FOTO_ODOMETRO',
  CONFIRMACION_KM: 'TANQUEO_CONFIRMACION_KM',
  KM_MANUAL: 'TANQUEO_KM_MANUAL',
  ESPERANDO_FACTURA_MANUAL: 'TANQUEO_ESPERANDO_FACTURA_MANUAL',
  ESPERANDO_LITROS_MANUAL: 'TANQUEO_ESPERANDO_LITROS_MANUAL',
  COMPLETAR_TIPO_COMBUSTIBLE: 'TANQUEO_COMPLETAR_TIPO_COMBUSTIBLE',
  COMPLETAR_VALOR: 'TANQUEO_COMPLETAR_VALOR',
  COMPLETAR_ESTACION: 'TANQUEO_COMPLETAR_ESTACION',
  CONFIRMACION_FINAL: 'TANQUEO_CONFIRMACION_FINAL'
};

module.exports = { ESTADOS: ESTADOS };
